import { Platform, Share } from 'react-native';
import type { Category, Transaction } from '@/store/types';
import { formatDate } from './finance';

const escapeCsv = (v: string) => {
  if (v.includes(',') || v.includes('"') || v.includes('\n')) {
    return `"${v.replace(/"/g, '""')}"`;
  }
  return v;
};

export const buildCSV = (txs: Transaction[], categories: Category[]) => {
  const header = ['Date', 'Type', 'Amount', 'Currency', 'Category', 'Subcategory', 'Merchant', 'Notes'];
  const rows = txs.map((t) => {
    const cat = categories.find((c) => c.id === t.categoryId);
    const sub = t.subcategoryId ? categories.find((c) => c.id === t.subcategoryId) : null;
    return [
      formatDate(t.date),
      t.type,
      t.amount.toFixed(2),
      t.currency,
      cat?.name ?? '',
      sub?.name ?? '',
      t.merchant ?? '',
      t.notes ?? '',
    ].map((v) => escapeCsv(String(v)));
  });
  return [header.join(','), ...rows.map((r) => r.join(','))].join('\n');
};

export const buildHTML = ({
  title,
  intro,
  sections,
}: {
  title: string;
  intro: string;
  sections: { heading: string; rows: { label: string; value: string; color?: string }[] }[];
}) => `<!doctype html>
<html>
<head><meta charset="utf-8"/><title>${title}</title>
<style>
body { font-family: -apple-system, Inter, Arial, sans-serif; color: #0A1628; padding: 32px; background: #FFFFFF; }
h1 { font-size: 28px; margin: 0; color: #0A1628; }
.subtitle { color: #6C7E9B; margin-top: 4px; }
h2 { font-size: 16px; margin-top: 28px; color: #0A1628; border-bottom: 2px solid #F4B942; padding-bottom: 6px; }
.row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #E6ECF5; }
.label { color: #4A5A78; font-size: 13px; }
.value { font-weight: 600; }
.footer { color: #A9B6CC; margin-top: 40px; font-size: 11px; }
</style>
</head>
<body>
<h1>${title}</h1>
<p class="subtitle">${intro}</p>
${sections
  .map(
    (s) => `
  <h2>${s.heading}</h2>
  ${s.rows
    .map(
      (r) =>
        `<div class="row"><span class="label">${r.label}</span><span class="value" style="color:${
          r.color ?? '#0A1628'
        }">${r.value}</span></div>`
    )
    .join('')}
`
  )
  .join('')}
<div class="footer">Generated by FinPulse · ${new Date().toLocaleString()}</div>
</body>
</html>`;

export const downloadWeb = (filename: string, content: string, mime: string) => {
  if (Platform.OS !== 'web') return;
  const g = globalThis as unknown as {
    Blob: new (parts: BlobPart[], options?: { type: string }) => Blob;
    URL: { createObjectURL: (b: Blob) => string; revokeObjectURL: (u: string) => void };
    document: Document;
  };
  const blob = new g.Blob([content], { type: mime });
  const url = g.URL.createObjectURL(blob);
  const a = g.document.createElement('a');
  a.href = url;
  a.download = filename;
  g.document.body.appendChild(a);
  a.click();
  a.remove();
  g.URL.revokeObjectURL(url);
};

export const openHtmlWeb = (html: string) => {
  if (Platform.OS !== 'web') return;
  const g = globalThis as unknown as { window: Window };
  const w = g.window.open('', '_blank');
  if (!w) return;
  w.document.write(html);
  w.document.close();
  setTimeout(() => {
    try {
      w.print();
    } catch {
      // ignore
    }
  }, 500);
};

export const shareText = async (title: string, message: string) => {
  try {
    await Share.share({ title, message });
  } catch {
    // ignore
  }
};
